### ISSUE TITLE
Broken precompilation on Linux?

### ISSUE THREAD

**Issue by natgeo-wong** [SpeedyWeather/SpeedyWeather.jl#294] opened 2023-04-08 02:56 UTC
The compilation works on my M1 Mac, but not on the cluster server Linux.  Below is the error:

```
[ Info: Precompiling SpeedyWeather [9e226e20-d153-4fed-8a5b-493def4f21a9]
WARNING: Method definition (::Type{SpeedyWeather.Parameters{Model} where Model<:SpeedyWeather.ModelSetup})() in module SpeedyWeather at util.jl:504 overwritten at /n/home07/nwong/.julia/packages/SpeedyWeather/4wdwa/src/default_parameters.jl:345.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition Type##kw(Any, Type{SpeedyWeather.Parameters{Model} where Model<:SpeedyWeather.ModelSetup}) in module SpeedyWeather at util.jl:504 overwritten at /n/home07/nwong/.julia/packages/SpeedyWeather/4wdwa/src/default_parameters.jl:345.
  ** incremental compilation may be fatally broken for this module **

ERROR: LoadError: syntax: unsupported `const` declaration on local variable around util.jl:515
Stacktrace:
 [1] top-level scope
   @ ~/.julia/packages/SpeedyWeather/4wdwa/src/physics/define_column.jl:1
 [2] include(mod::Module, _path::String)
   @ Base ./Base.jl:419
 [3] include(x::String)
   @ SpeedyWeather ~/.julia/packages/SpeedyWeather/4wdwa/src/SpeedyWeather.jl:1
 [4] top-level scope
   @ ~/.julia/packages/SpeedyWeather/4wdwa/src/SpeedyWeather.jl:120
 [5] include
   @ ./Base.jl:419 [inlined]
 [6] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
   @ Base ./loading.jl:1554
 [7] top-level scope
   @ stdin:1
in expression starting at /n/home07/nwong/.julia/packages/SpeedyWeather/4wdwa/src/physics/define_column.jl:1
in expression starting at /n/home07/nwong/.julia/packages/SpeedyWeather/4wdwa/src/SpeedyWeather.jl:1
in expression starting at stdin:1
ERROR: Failed to precompile SpeedyWeather [9e226e20-d153-4fed-8a5b-493def4f21a9] to /n/home07/nwong/.julia/compiled/v1.8/SpeedyWeather/jl_1Ku4mq.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
   @ Base ./loading.jl:1705
 [3] compilecache
   @ ./loading.jl:1649 [inlined]
 [4] _require(pkg::Base.PkgId)
   @ Base ./loading.jl:1337
 [5] _require_prelocked(uuidkey::Base.PkgId)
   @ Base ./loading.jl:1200
 [6] macro expansion
   @ ./loading.jl:1180 [inlined]
 [7] macro expansion
   @ ./lock.jl:223 [inlined]
 [8] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:1144
```

I'm sorry I don't have more information. I did try to find this `util.jl` but it is nowhere to be found.  I ran into this error even when installing on a separate environment from the main environment (i.e. SpeedyWeather is the only package).

**Comment by milankl** [comment] 2023-04-08 04:29
Sorry we dropped v1.7 support in main. Please use 1.8, the const annotation is only available in 1.8 that’s probably the whole errorOn 7 Apr 2023, at 22:57, Nathanael Wong ***@***.***> wrote:﻿
The compilation works on my M1 Mac, but not on the cluster server Linux.  Below is the error:
[ Info: Precompiling SpeedyWeather [9e226e20-d153-4fed-8a5b-493def4f21a9]
WARNING: Method definition (::Type{SpeedyWeather.Parameters{Model} where Model<:SpeedyWeather.ModelSetup})() in module SpeedyWeather at util.jl:504 overwritten at /n/home07/nwong/.julia/packages/SpeedyWeather/4wdwa/src/default_parameters.jl:345.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition Type##kw(Any, Type{SpeedyWeather.Parameters{Model} where Model<:SpeedyWeather.ModelSetup}) in module SpeedyWeather at util.jl:504 overwritten at /n/home07/nwong/.julia/packages/SpeedyWeather/4wdwa/src/default_parameters.jl:345.
  ** incremental compilation may be fatally broken for this module **

ERROR: LoadError: syntax: unsupported `const` declaration on local variable around util.jl:515
Stacktrace:
 [1] top-level scope
   @ ~/.julia/packages/SpeedyWeather/4wdwa/src/physics/define_column.jl:1
 [2] include(mod::Module, _path::String)
   @ Base ./Base.jl:419
 [3] include(x::String)
   @ SpeedyWeather ~/.julia/packages/SpeedyWeather/4wdwa/src/SpeedyWeather.jl:1
 [4] top-level scope
   @ ~/.julia/packages/SpeedyWeather/4wdwa/src/SpeedyWeather.jl:120
 [5] include
   @ ./Base.jl:419 [inlined]
 [6] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
   @ Base ./loading.jl:1554
 [7] top-level scope
   @ stdin:1
in expression starting at /n/home07/nwong/.julia/packages/SpeedyWeather/4wdwa/src/physics/define_column.jl:1
in expression starting at /n/home07/nwong/.julia/packages/SpeedyWeather/4wdwa/src/SpeedyWeather.jl:1
in expression starting at stdin:1
ERROR: Failed to precompile SpeedyWeather [9e226e20-d153-4fed-8a5b-493def4f21a9] to /n/home07/nwong/.julia/compiled/v1.8/SpeedyWeather/jl_1Ku4mq.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool)
   @ Base ./loading.jl:1705
 [3] compilecache
   @ ./loading.jl:1649 [inlined]
 [4] _require(pkg::Base.PkgId)
   @ Base ./loading.jl:1337
 [5] _require_prelocked(uuidkey::Base.PkgId)
   @ Base ./loading.jl:1200
 [6] macro expansion
   @ ./loading.jl:1180 [inlined]
 [7] macro expansion
   @ ./lock.jl:223 [inlined]
 [8] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:1144

I'm sorry I don't have more information. I did try to find this util.jl but it is nowhere to be found.  I ran into this error even when installing on a separate environment from the main environment (i.e. SpeedyWeather is the only package).

**Comment by navidcy** [comment] 2023-04-08 05:15
> Sorry we dropped v1.7 support in main. Please use 1.8, the const annotation is only available in 1.8 that’s probably the whole errorOn 7 Apr 2023, at 22:57, Nathanael Wong ***@***.***> wrote:﻿ The compilation works on my M1 Mac, but not on the cluster server Linux. Below is the error: [ Info: Precompiling SpeedyWeather [9e226e20-d153-4fed-8a5b-493def4f21a9] WARNING: Method definition (::Type{SpeedyWeather.Parameters{Model} where Model<:SpeedyWeather.ModelSetup})() in module SpeedyWeather at util.jl:504 overwritten at /n/home07/nwong/.julia/packages/SpeedyWeather/4wdwa/src/default_parameters.jl:345. ** incremental compilation may be fatally broken for this module ** WARNING: Method definition Type##kw(Any, Type{SpeedyWeather.Parameters{Model} where Model<:SpeedyWeather.ModelSetup}) in module SpeedyWeather at util.jl:504 overwritten at /n/home07/nwong/.julia/packages/SpeedyWeather/4wdwa/src/default_parameters.jl:345. ** incremental compilation may be fatally broken for this module ** ERROR: LoadError: syntax: unsupported `const` declaration on local variable around util.jl:515 Stacktrace: [1] top-level scope @ ~/.julia/packages/SpeedyWeather/4wdwa/src/physics/define_column.jl:1 [2] include(mod::Module, _path::String) @ Base ./Base.jl:419 [3] include(x::String) @ SpeedyWeather ~/.julia/packages/SpeedyWeather/4wdwa/src/SpeedyWeather.jl:1 [4] top-level scope @ ~/.julia/packages/SpeedyWeather/4wdwa/src/SpeedyWeather.jl:120 [5] include @ ./Base.jl:419 [inlined] [6] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing) @ Base ./loading.jl:1554 [7] top-level scope @ stdin:1 in expression starting at /n/home07/nwong/.julia/packages/SpeedyWeather/4wdwa/src/physics/define_column.jl:1 in expression starting at /n/home07/nwong/.julia/packages/SpeedyWeather/4wdwa/src/SpeedyWeather.jl:1 in expression starting at stdin:1 ERROR: Failed to precompile SpeedyWeather [9e226e20-d153-4fed-8a5b-493def4f21a9] to /n/home07/nwong/.julia/compiled/v1.8/SpeedyWeather/jl_1Ku4mq. Stacktrace: [1] error(s::String) @ Base ./error.jl:35 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, keep_loaded_modules::Bool) @ Base ./loading.jl:1705 [3] compilecache @ ./loading.jl:1649 [inlined] [4] _require(pkg::Base.PkgId) @ Base ./loading.jl:1337 [5] _require_prelocked(uuidkey::Base.PkgId) @ Base ./loading.jl:1200 [6] macro expansion @ ./loading.jl:1180 [inlined] [7] macro expansion @ ./lock.jl:223 [inlined] [8] require(into::Module, mod::Symbol) @ Base ./loading.jl:1144 I'm sorry I don't have more information. I did try to find this util.jl but it is nowhere to be found. I ran into this error even when installing on a separate environment from the main environment (i.e. SpeedyWeather is the only package). —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Then let’s change the compatibility req in Project.toml?

**Comment by milankl** [comment] 2023-04-08 14:03
Of course yes! I knew I forgot something 😅

**Comment by natgeo-wong** [comment] 2023-04-08 16:11
I actually use v1.8.0 tho hahaha

**Comment by natgeo-wong** [comment] 2023-04-08 16:20
Alright, it looks like v1.8.0 didn't work but v1.8.5 does so HAPPY TIMES FOR ME

**Comment by navidcy** [comment] 2023-04-08 22:11
Strange!

**Comment by navidcy** [comment] 2023-04-09 01:58
```Julia
] up
``
in case one of the deps were "happy" with v1.7 and the lack of compat entry to 1.8 didn't enforce them to update?

**Comment by milankl** [comment] 2023-04-10 18:01
Agree, probably something like that. I'll leave that issue open for now in case other precompilation issues show up we can post them here.

**Comment by milankl** [comment] 2023-05-22 23:59
duplicate of #296

**Closed by milankl** 2023-05-22 23:59 UTC
Labels: dependency, compatibility
